#!/bin/bash
# addstatic
# KD4Z
# Version:  3.04
# script to add static DMR ids into the usersCSV after glv
# requires a simple file that mimics the exact field layout of user.bin
# must contain seven fields, separated by commas
# (that means 6 commas per line)
# leave field blank if no data is needed for a given field
#
# filename containing static user data is named: static.users
#
# Example:
#  privateID1,call1,name1,city1,state1,nickname1,country1
#  privateID2,call2,name2,,,nickname2,
#  privateID3,call3,name3,,,,
#
# useage:
#  This script is automatically called from exec.post
#  no need to call this manually anymore. In fact, don't.
# 


FILESTATIC=~/static.users
FILESEED=user.seed
FILESEEDZIP=seeds.zip

if [ ! -f $FILESTATIC ]; then
  touch $FILESTATIC
fi

if [ -f ~/keep.seed.file ] && [ -f ~/seeds.zip ]; then
    cp ~/seeds.zip .
else  
  rm $FILESEEDZIP
fi

if [ ! -f $FILESEEDZIP ]; then
  timeout 8 wget https://raw.githubusercontent.com/KD4Z/md380tools-vm/master/seeds.zip -O $FILESEEDZIP
fi

if [ ! -f $FILESEEDZIP ]; then
  echo -e "${RED}Unable to download seed file for static EU data.${NC}"
  sleep 8
fi

if [ -f $FILESTATIC ]; then
  cat $FILESTATIC >userall.tmp
  if [ -f $FILESEEDZIP ]; then
    unzip $FILESEEDZIP $FILESEED >/dev/null
    cat $FILESEED ~/user.bin >>userall.tmp
    if [ -f ~/keep.seed.file ]; then
		echo -e "${GREEN}Keeping seed file for next ${YELLOW}glv${NC}."
		echo -e "${GREEN}To force an update next glv: rm ~/keep.seed.file"
		cp $FILESEEDZIP ~
		sleep 1
		
	fi
	rm $FILESEED $FILESEEDZIP
    
	cat $FILESTATIC ~/user.bin >>userall.tmp
  fi
  awk -F',' '!seen[$1]++' userall.tmp >user.tmp
  sort -t, -k 1,1 -n user.tmp >usersorted.tmp
  
  sed -i 1,1d usersorted.tmp
  
  cat usersorted.tmp >~/user.bin
  rm userall.tmp usersorted.tmp user.tmp
  wc --lines ~/md380tools/db/dmrmarc.tmp
  echo -e "${GREEN}Static DMR ID Import completed.  ID count on the line above.${NC}"
else
  echo -e "${RED}Could not find file containing static user info. Filename${WHITE} '$FILE' ${NC}"
fi
