#!/bin/bash
# addstatic
# KD4Z
# Version:  3.04
# script to add static DMR ids into the usersCSV after glv
# requires a simple file that mimics the exact field layout of user.bin
# must contain seven fields, separated by commas
# (that means 6 commas per line)
# leave field blank if no data is needed for a given field
#
# filename containing static user data is named: static.users
#
# Example:
#  privateID1,call1,name1,city1,state1,nickname1,country1
#  privateID2,call2,name2,,,nickname2,
#  privateID3,call3,name3,,,,
#
# useage:
#  This script is automatically called from exec.post
#  no need to call this manually anymore. In fact, don't.
# 


FILESTATIC=~/static.users
FILESEED=user.seed
FILESEEDZIP=seeds.zip
STATICFILEHOST=~/static.host
TMPALL=~/userall.tmp
TMPDEDUP=~/dedup.tmp
TMPSORTED=~/sorted.tmp

if [ -f $TMPALL ]; then
	rm $TMPALL
fi
touch $TMPALL

if [ -f $STATICFILEHOST ]; then
  timeout 8 wget -i $STATICFILEHOST -O $FILESTATIC
fi

if [ -f $FILESTATIC ]; then
  sed -i -e 's/\r//' $FILESTATIC
else
  touch $FILESTATIC
fi

if [ -f ~/keep.seed.file ] && [ -f ~/seeds.zip ]; then
    cp ~/seeds.zip .
else  
  rm $FILESEEDZIP
fi

if [ ! -f $FILESEEDZIP ]; then
  timeout 8 wget https://raw.githubusercontent.com/KD4Z/md380tools-vm/master/seeds.zip -O $FILESEEDZIP
fi

if [ ! -f $FILESEEDZIP ]; then
  echo -e "${RED}Unable to download seed file for static EU data.${NC}"
  sleep 8
fi

if [ -f $FILESTATIC ]; then
  cat $FILESTATIC >>$TMPALL
fi
  
if [ -f $FILESEEDZIP ]; then
    if [ -f $FILESEED ]; then
	  rm $FILESEED
	fi
    unzip $FILESEEDZIP $FILESEED >/dev/null
    cat $FILESEED >>$TMPALL
    if [ -f ~/keep.seed.file ]; then
		echo -e "${GREEN}Keeping seed file for next ${YELLOW}glv${NC}."
		echo -e "${GREEN}To force an update next glv: rm ~/keep.seed.file"
		cp $FILESEEDZIP ~
		sleep 1
		
	fi
	if [ -f ~/keep.tmp ]; then
	  rm $FILESEED $FILESEEDZIP
	fi
fi
  
if [ -f $FILESTATIC ]; then
    cat $FILESTATIC >>$TMPALL
fi
cat ~/user.bin >>$TMPALL
  
awk -F',' '!seen[$1]++' $TMPALL >$TMPDEDUP
sort -t, -k 1,1 -n $TMPDEDUP >$TMPSORTED
  
#sed -i 1,1d usersorted.tmp  # strip header
  
cat $TMPSORTED >~/user.bin
  
if [ -f ~/keep.tmp ]; then
    rm $TMPALL $TMPSORTED 
fi

wc --lines ~/md380tools/db/dmrmarc.tmp
echo -e "${GREEN}Static DMR ID Import completed.  ID count on the line above.${NC}"
