#!/bin/bash
# KD4Z
# Version:  3.0
# called after git pull, and before everything else, use to setup script exec mode
if [ -d ~/save ] && [ ! -d ~/archive ]; then
  mv ~/save ~/archive
fi
if [ ! -d ~/archive ]; then
  md ~/archive
fi
if [ -f ~/md380tools-vm/exec.pre ]; then
  chmod +x ~/md380tools-vm/exec.pre
fi
if [ -f ~/md380tools-vm/menuopts ]; then
  chmod +x ~/md380tools-vm/menuopts
fi
if [ -f ~/md380tools-vm/exec.post ]; then
  chmod +x ~/md380tools-vm/exec.post  
fi
if [ -f ~/md380tools-vm/addstatic ]; then
  chmod +x ~/md380tools-vm/addstatic
fi
if [ -f ~/md380tools-vm/flashdb ]; then
  chmod +x ~/md380tools-vm/flashdb
fi
if [ -f ~/md380tools-vm/recipes ]; then
  chmod +x ~/md380tools-vm/recipes
fi
if [ -f ~/md380tools-vm/lookup ]; then
  chmod +x ~/md380tools-vm/lookup
fi
if [ -f ~/md380tools-vm/tweakopts ]; then
  chmod +x ~/md380tools-vm/tweakopts
fi
if [ -f ~/md380tools-vm/root/flashdb ]; then
  cp ~/md380tools-vm/root/flashdb ~
  chmod +x ~/flashdb
fi
if [ -f ~/md380tools-vm/root/lookup ]; then
  cp ~/md380tools-vm/root/lookup ~
  chmod +x ~/lookup
fi
if [ -f ~/md380tools-vm/filter.sys ]; then
  chmod +x ~/md380tools-vm/filter.sys
fi
if [ -f ~/md380tools-vm/root/tweaks ]; then
  cp ~/md380tools-vm/root/tweaks ~
  chmod +x ~/tweaks
fi
if [ -f ~/md380tools-vm/root/save ]; then
  cp ~/md380tools-vm/root/save ~
  chmod +x ~/save
fi
if [ -f ~/md380tools-vm/root/restore ]; then
  cp ~/md380tools-vm/root/restore ~
  chmod +x ~/restore
fi
cp ~/md380tools-vm/menuopts ~
chmod +x ~/menuopts

