#!/bin/bash
# install_static
# KD4Z  
# Version:  1
# script to add install the script that imports static DMR ids into the usersCSV after glv
# To install or update the addstatic script, run this from the tyt home directory prompt
#
#  wget https://raw.githubusercontent.com/KD4Z/md380tools-vm/master/install_static -O install_static && bash ./install_static

wget https://raw.githubusercontent.com/KD4Z/md380tools-vm/master/addstatic -O addstatic
wget https://raw.githubusercontent.com/KD4Z/md380tools-vm/master/static.users.example -O static.users.example
wget https://raw.githubusercontent.com/KD4Z/md380tools-vm/master/static.users -O static.users
chmod +x addstatic
clear
echo "addstatic script installed or updated successfully"
echo "Use nano to edit the file called 'static.users' using the example file 'static.users.example' as a guide"
echo "Then run glv, followed by ./addstatic, then flashdb" 
