#!/bin/bash
# install_static
# KD4Z  
# Version:  1
# script to add install the script that imports static DMR ids into the usersCSV after glv
# To install or update the addstatic script, run this from the tyt home directory prompt
#
#  wget https://github.com/KD4Z/md380tools-vm/blob/master/install_static && sudo bash install_static

wget https://github.com/KD4Z/md380tools-vm/blob/master/addstatic
wget https://github.com/KD4Z/md380tools-vm/blob/master/static.users.sample  
chmod +x addstatic

echo "Create a file called 'static.users' using the example file 'static.users.example' as a guide"
echo "Then run glv, followed by ./addstatic, then flashdb" 
