#!/bin/bash 

if [ ! -f /etc/motd.save ]; then
  . ~/md380tools-vm/root/.bash_aliases
fi
. ~/md380tools-vm/strings

count=$(wc --lines ~/user.bin | cut -d" " -f1)
clear
echo -e "                ${WHITE}${ZPROJ} (v3.07)${NC}\t  ${RED}(${ZCOUNT1} ${count})${NC}"
echo -e ""
echo -e " ${ZMESS11}"
echo -e " ${ZMESS12}"
echo -e " ${ZMESS13}"
echo -e " ${ZMESS14}"
echo -e ""
echo -e " ${ZMESS15}"
echo -e " ${ZMESS16}"
#echo -e " ${ZMESS17}"
echo -e ""
echo -e "  ${YELLOW}${ZCOM1}${NC}      -- (${YELLOW}G${NC}et ${YELLOW}L${NC}atest ${YELLOW}V${NC}ersion) ${ZCOM11}"
echo -e "  ${YELLOW}${ZCOM10}${NC} --  ${ZCOM12}"
echo -e ""
echo -e " ${ZSEL4}"
echo -e ""
echo -e "  ${YELLOW}${ZCOM2}${NC}    -- ${RED}(DFU)${NC} ${ZWRITE1} (${ZRAD10})"
echo -e "  ${YELLOW}${ZCOM3}${NC} -- ${RED}(DFU)${NC} ${ZWRITE2} (${ZRAD20})"
echo -e "  ${YELLOW}${ZCOM4}${NC}  -- ${RED}(ON) ${NC} ${ZWRITE3}"
echo -e ""
echo -e "  ${YELLOW}${ZCOM5}${NC} ${BLUE}${ZCOM51}${NC} -- ${ZWRITE4} "
echo -e ""
echo -e "\t\t\t${YELLOW}menu${NC}     -- ${ZMESS61} (or ${WHITE}Ctrl-D${NC})"
echo -e "\t\t\t${YELLOW}help${NC}     -- ${ZMESS71}"
echo -e ""
