#!/bin/bash 
# KD4Z
# Version:  4.40
# main menu

if [ ! -f /etc/motd.save ]; then
  . ~/md380tools-vm/root/.bash_aliases
fi
. ~/md380tools-vm/strings

countmarc=$(wc --lines ~/user.bin | cut -d" " -f1)
userbinsize=$(ls -l ~/user.bin | cut -d" " -f5)
clear


if (( countmarc < 80000 )); then
  cntcolor=${RED}
else
  cntcolor=${GREEN}
fi
 
vers="4.40"
 

echo -e " ${WHITE}${ZPROJ} (v${vers})${NC}\t  (${ZCOUNT1}${cntcolor} ${countmarc} / ${userbinsize}${NC} bytes)"
	
echo -e ""
echo -e " ${ZMESS11}"
echo -e " ${ZMESS12}"
#if [ -f /etc/motd.save ]; then
#  echo -e " ${ZMESS13}"
#  echo -e " ${ZMESS14}"
#fi
echo -e ""
echo -e " ${ZMESS15}"
if [ -f /etc/motd.save ]; then
   echo -e " ${ZMESS16}"
  #echo -e " ${ZMESS17}"
fi
echo -e ""
echo -e -n "  ${YELLOW}${ZCOM1}${NC}      -- (${YELLOW}G${NC}et ${YELLOW}L${NC}atest ${YELLOW}V${NC}ersion) ${ZCOM11}"
if [ -f ~/md380tools-vm/glv.mike ]; then
  echo -e -n " ${RED}(Mike)"
fi
if [ -f ~/md380tools-vm/glv.wolf ]; then
  echo -e -n " ${RED}(Wolf)"
fi

echo -e "${NC}"
echo -e "  ${YELLOW}${ZCOM10}${NC} --  ${ZCOM12}"
echo -e ""
echo -e " ${ZSEL4}"
echo -e ""
if [ ! -f ~/firmware-noGPS.bin ]; then
  echo -e "  ${YELLOW}${ZCOM2}${NC}    -- ${RED} Not available.  Run ${YELLOW}glv ${RED}again${NC}"
else
  echo -e "  ${YELLOW}${ZCOM2}${NC}    -- ${RED}(DFU)${NC} ${ZWRITE1} (${ZRAD10})"
fi

if [ ! -f ~/firmware-GPS.bin ]; then
  echo -e "  ${YELLOW}${ZCOM3}${NC}    -- ${RED} Not available.  Run ${YELLOW}glv ${RED}again${NC}"
else
  echo -e "  ${YELLOW}${ZCOM3}${NC} -- ${RED}(DFU)${NC} ${ZWRITE2} (${ZRAD20})"
fi

if [ ! -f ~/user.bin ]; then
  echo -e "  ${YELLOW}${ZCOM4}${NC}    -- ${RED} Not available.  Run ${YELLOW}glv ${RED}or ${YELLOW}glvusers ${RED}again{NC}"
else
  echo -e "  ${YELLOW}${ZCOM4}${NC}  -- ${RED}(${ZCOM24}) ${NC} ${ZWRITE3}"
fi

echo -e ""
echo -e "  ${YELLOW}${ZCOM5}${NC} ${BLUE}${ZCOM51}${NC} -- ${ZWRITE4} "

echo -e ""
echo -e -n "\t${YELLOW}menu${NC}     -- ${ZMESS61}${NC}"
if [ -f /etc/motd.save ]; then
  echo -e " (${ZCOM20} ${WHITE}Ctrl+D${NC})"
else
  echo -e ""
fi
echo -e "\t${YELLOW}${ZCOM8}${NC}   -- ${ZCOM22}"
echo -e "\t${YELLOW}help${NC}     -- ${ZMESS71}"
echo -e ""
