#!/bin/bash 
clear
echo -e "                  ${WHITE}KD4Z - md380tools-vm - Recipes ${NC}"
echo -e ""
echo -e " ${WHITE}MD-380 / Retevis RT3 / No GPS${NC}"
echo -e ""
echo -e "  ${YELLOW}glv${NC}"
echo -e "  ${YELLOW}flash${NC}"
echo -e "  ${YELLOW}flashdb${NC}"
echo -e ""
echo -e " ${WHITE}MD-390 / Retevis RT8 / with GPS${NC}"
echo -e ""
echo -e "  ${YELLOW}glv${NC}"
echo -e "  ${YELLOW}flashgps${NC}"
echo -e "  ${YELLOW}flashdb${NC}"
echo -e ""
echo -e " ${WHITE}Update UsersCSV Contact Data only${NC}"
echo -e ""
echo -e "  ${YELLOW}glv${NC}"
echo -e "  ${YELLOW}flashdb${NC}"
echo -e ""
echo -e "\t\t\t${YELLOW}~/tweaks${NC} -- Experimental tweaks menu"
echo -e "\t\t\t${YELLOW}menu${NC} -- Back to main menu (or ${WHITE}Ctrl-D${NC})"
echo -e ""



