#!/bin/bash 
. ~/md380tools-vm/strings
clear
echo -e "                ${WHITE}${ZPROJ} - ${ZRECIPS}${NC}"
echo -e ""
echo -e -n " ${WHITE}${ZRAD10} / ${ZRAD11}${NC}:"
echo -e "\t\t\t${YELLOW}${ZCOM1}  ${ZCOM2}  ${ZCOM4}${NC}"
echo -e ""
echo -e -n " ${WHITE}${ZRAD20} / ${ZRAD12}${NC}:"
echo -e "\t\t${YELLOW}${ZCOM1}  ${ZCOM3}  ${ZCOM4}${NC}"
echo -e ""
echo -e -n " ${WHITE}${ZCOM12}${NC}:"
echo -e "\t${YELLOW}${ZCOM10}  ${ZCOM4}${NC}"
echo -e ""
echo -e " ${WHITE}${ZCOM16}${NC}:"
echo -e "\t${YELLOW}${ZCOM17}${NC} ${BLUE}${ZCOM19}${NC}"
echo -e "\t${YELLOW}${ZCOM18}${NC} ${BLUE}${ZCOM19}${NC} ${ZCOM20} ${YELLOW}${ZCOM18}${NC} ${ZCOM21}"
echo -e "\t${YELLOW}${ZCOM18}${BLUE} X${NC}\t\t-- ${ZCOM46} ( X => 1 to 9)${NC}"
echo -e "\t${YELLOW}${ZCOM18}${BLUE} stable${NC}\t\t-- ${ZCOM45}"
echo -e ""
echo -e " ${WHITE}Recover Locked Radio:${NC}"
echo -e "\t${YELLOW}${ZCOM9}${NC}\t\t-- ${ZCOM47}"
echo -e "\t${YELLOW}rdtblank${NC}\t\t-- ${RED}Force Blank Codeplug to Radio${NC}"
echo -e ""

echo -e " ${WHITE}Utility:${NC}"
echo -e "\t${YELLOW}snap ${BLUE}filename.bmp${NC}       -- Create screenshot in 'screenshot' folder.  Must be named .bmp"
echo -e "\t${YELLOW}rdtread ${BLUE}codeplug.bin${NC}    -- Read codeplug out of radio into binary file."
echo -e "\t${YELLOW}rdtwrite ${BLUE}codeplug.rdt${NC}   -- Write codeplug to radio from RDT,DFU or BIN file."
echo -e ""
if [ -f /etc/kd4z.toolkit.4 ] && [ -f /etc/motd.save ]; then
  echo -e "\t${YELLOW}shutdown${NC} or ${YELLOW}reboot${NC}      -- Safely Shutdown or Reboot the Virtual Machine"
  echo -e ""
  echo -e "\t${YELLOW}stats${NC}                   -- VM information menu"
fi
echo -e "\t${YELLOW}${ZCOM8}${NC}\t\t\t-- ${ZCOM22}"
echo -e -n "\t${YELLOW}menu${NC}\t\t\t-- Back to main menu "
if [ -f /etc/motd.save ]; then
  echo -e " (${ZCOM20} ${WHITE}Ctrl+D${NC})"
else
  echo -e ""
fi
echo -e ""
