#!/bin/bash 
. ~/md380tools-vm/strings
clear
echo -e "                  ${WHITE}KD4Z - md380tools - Tweaks ${NC}"
echo -e ""
echo -e " ${ZCOM32}"
echo -e " ${ZCOM33}"
echo -e ""
echo -e "  ${ZCOM39} ${ZCOM36}: ${ZCOM30}${NC}    ${ZCOM40} ${ZCOM36}:  ${NC}${ZCOM31}${NC}"
echo -e ""
echo -e "  ${ZCOM37}:  ${YELLOW}${ZCOM29}${NC} ~/volumebar.enable"
echo -e ""
echo -e " ${WHITE}-- tweakfile list  --${NC}"
echo -e -n "  ${BLUE}~/extra.data.disable${NC}  ${ZCOM43} ${ZCOM48}" 
if [ -f ~/extra.data.disable ]; then
 echo -e "${RED} *${NC}"
else
 echo -e ""
fi

echo -e -n "  ${BLUE}~/volumebar.enable${NC}  ${ZCOM42} ${ZCOM49}"
if [ -f ~/volumebar.enable ]; then
 echo -e "${RED} *${NC}"
else
 echo -e ""
fi

echo -e -n "  ${BLUE}~/pttlastheard.disable${NC}  ${ZCOM43} ${ZCOM52}"
if [ -f ~/pttlastheard.disable ]; then
	echo -e "${RED} *${NC}"
else
	echo -e ""
	echo -e -n "  ${BLUE}~/pttcountup.enable${NC}  ${ZCOM42} ${ZCOM53}"
	if [ -f ~/pttcountup.enable ]; then
		echo -e "${RED} *${NC}"
	else
		echo -e ""
	fi
fi

echo -e -n "  ${BLUE}~/legacyrxscreen.enable${NC}  ${ZCOM42} ${ZCOM62}"
if [ -f ~/legacyrxscreen.enable ]; then
	echo -e "${RED} *${NC}"
else
	echo -e ""
	echo -e -n "  ${BLUE}~/blackfontrxscreen.enable${NC}  ${ZCOM42} ${ZCOM63}"
	if [ -f ~/blackfontrxscreen.enable ]; then
		echo -e "${RED} *${NC}"
	else
		echo -e ""
	fi
fi


echo -e -n "  ${BLUE}~/lang.nl${NC}     ${ZCOM42} Dutch text"
if [ -f ~/lang.nl ]; then
 echo -e "${RED} *${NC}"
else
 echo -e ""
fi
echo -e -n "  ${BLUE}~/lang.pt${NC}     ${ZCOM42} Portuguese text"
if [ -f ~/lang.pt ]; then
 echo -e "${RED} *${NC}"
else
 echo -e ""
fi
echo -e -n "  ${BLUE}~/lang.it${NC}     ${ZCOM42} Italian text"
if [ -f ~/lang.it ]; then
 echo -e "${RED} *${NC}"
else
 echo -e ""
fi
echo -e -n "  ${BLUE}~/lang.es${NC}     ${ZCOM42} Spanish text"
if [ -f ~/lang.es ]; then
 echo -e "${RED} *${NC}"
else
 echo -e ""
fi
echo -e -n "  ${BLUE}~/lang.de${NC}     ${ZCOM42} German text"
if [ -f ~/lang.de ]; then
 echo -e "${RED} *${NC}"
else
 echo -e ""
fi
echo -e -n "  ${BLUE}~/lang.fr${NC}     ${ZCOM42} French text"
if [ -f ~/lang.fr ]; then
 echo -e "${RED} *${NC}"
else
 echo -e ""
fi
echo -e -n "  ${BLUE}~/lang.sl${NC}     ${ZCOM42} Slovenian text"
if [ -f ~/lang.sl ]; then
 echo -e "${RED} *${NC}"
else
 echo -e ""
fi
echo -e ""
echo -e -n " ${YELLOW}menu${NC} -- Back to main menu "
if [ -f /etc/motd.save ]; then
  echo -e " (${ZCOM20} ${WHITE}Ctrl+D${NC})"
else
  echo -e ""
fi
echo -e ""
