#!/bin/bash 
. ~/md380tools-vm/strings
clear
echo -e "                  ${WHITE}KD4Z - md380tools-vm - Tweaks ${NC}"
echo -e ""
echo -e " ${ZCOM32}"
echo -e " ${ZCOM33}"
echo -e ""
echo -e "  ${ZCOM39} ${ZCOM36}: ${ZCOM30}${NC}    ${ZCOM40} ${ZCOM36}:  ${NC}${ZCOM31}${NC}"
echo -e ""
echo -e "  ${ZCOM37}:  ${YELLOW}${ZCOM29}${NC} ~/filter.countries.disable"
echo -e ""
echo -e " ${WHITE}-- tweakfile list  --${NC}"
echo -e ""
echo -e -n "  ${BLUE}~/filter.countries.disable${NC}  ${ZCOM43} ${ZCOM41} ${ZCOM38}"
if [ -f ~/filter.countries.disable ]; then
 echo -e "${RED} *${NC}"
else
 echo -e ""
fi
echo -e -n "  ${BLUE}~/filter.us.states.disable${NC}  ${ZCOM43} US State ${ZCOM38}"
if [ -f ~/filter.us.states.disable ]; then
 echo -e "${RED} *${NC}"
else
 echo -e ""
fi
echo -e -n "  ${BLUE}~/filter.sys.disable${NC}        ${ZCOM43} all filters"
if [ -f ~/filter.sys.disable ]; then
 echo -e "${RED} *${NC}"
else
 echo -e ""
fi
echo -e -n "  ${BLUE}~/fill.nickname.disable${NC}     ${ZCOM43} ${ZCOM44}"
if [ -f ~/fill.nickname.disable ]; then
 echo -e "${RED} *${NC}"
else
 echo -e ""
fi
echo -e -n "  ${BLUE}~/lang.nl${NC}     ${ZCOM42} Dutch text"
if [ -f ~/lang.nl ]; then
 echo -e "${RED} *${NC}"
else
 echo -e ""
fi
echo -e -n "  ${BLUE}~/lang.pt${NC}     ${ZCOM42} Portuguese text"
if [ -f ~/lang.pt ]; then
 echo -e "${RED} *${NC}"
else
 echo -e ""
fi
echo -e -n "  ${BLUE}~/lang.it${NC}     ${ZCOM42} Italian text"
if [ -f ~/lang.it ]; then
 echo -e "${RED} *${NC}"
else
 echo -e ""
fi
echo -e -n "  ${BLUE}~/lang.es${NC}     ${ZCOM42} Spanish text"
if [ -f ~/lang.es ]; then
 echo -e "${RED} *${NC}"
else
 echo -e ""
fi

echo -e ""
echo -e -n " ${YELLOW}menu${NC} -- Back to main menu "
if [ -f /etc/motd.save ]; then
  echo -e " (${ZCOM20} ${WHITE}Ctrl+D${NC})"
else
  echo -e ""
fi
echo -e ""
