#!/bin/bash
# flashidb
# KD4Z
# Version:  4.6
# writes indexeduser.bin to radio  This is a compressed version of user.bin and requires lastest firmware for proper display

 
if [ -f ~/indexeduser.bin ]; then
  echo 
  echo -e "${YELLOW}Writing indexeduser.bin to radio.  Requires latest firmware for compressed data support."
   echo -e "${GREEN}Radio should be just turned ${RED}ON ${GREEN}(${RED}not DFU mode${GREEN}) and connected to USB port.${NC}"
  sleep 2
  ~/md380tools/md380-tool spiflashwrite ~/indexeduser.bin 0x100000
else
  echo "${RED}indexeduser.bin file not present.  ${YELLOW}Run glv or glvusers first."
fi
sleep 5
cd ~ 
~/md380tools-vm/menuopts
 

